# Generated by Django 5.1.7 on 2025-04-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandFlow_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='designvisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
