# Generated by Django 5.1.7 on 2025-04-03 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandFlow_', '0002_designvisual_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignUser',
            fields=[
                ('idCampaignUser', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=100)),
                ('asigned_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaingn',
            fields=[
                ('idcampaingn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('description', models.TextField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idcategory', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idorder', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('addres', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='designvisual',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.AddField(
            model_name='campaignuser',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandFlow_.campaingn'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandFlow_.user'),
        ),
        migrations.AddField(
            model_name='campaignuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandFlow_.user'),
        ),
    ]
