# Generated by Django 5.1.7 on 2025-04-08 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandFlow_', '0003_campaignuser_campaingn_category_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.IntegerField()),
                ('url_download', models.URLField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaignuser',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignuser',
            name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='iduser',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(default='cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('idorderdetails', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandFlow_.order')),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandFlow_.product')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('idreviews', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandFlow_.product')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandFlow_.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppCart',
            fields=[
                ('idshoppcart', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandFlow_.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppCartDetails',
            fields=[
                ('idshoppcartdetails', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandFlow_.product')),
                ('idshoppcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandFlow_.shoppcart')),
            ],
        ),
        migrations.DeleteModel(
            name='Campaingn',
        ),
        migrations.DeleteModel(
            name='CampaignUser',
        ),
    ]
